name: elm-format-test-lib
version: 0.0.0.1

synopsis: Test helpers used by elm-format-tests and elm-refactor-tests
license: BSD-3-Clause
license-file: LICENSE
author:     Aaron VonderHaar
maintainer: gruen0aermel@gmail.com
copyright:  See https://github.com/avh4/elm-format/blob/master/LICENSE

build-type: Simple

language: Haskell2010

default-extensions:
  - DeriveFunctor
  - LambdaCase
  - OverloadedStrings
  - ScopedTypeVariables

ghc-options:
  - -O2
  - -Wall
  - -Werror=unused-packages
  - -Wno-name-shadowing

dependencies:
  base: ">= 4.15.0.0 && < 5"
  containers: ">= 0.6.5.1 && < 0.7"
  filepath: ">= 1.4.2.1 && < 1.5"
  hspec: ">= 2.7.4 && < 3"
  hspec-core: ">= 2.7.4 && < 3"
  hspec-golden: ">= 0.2.0.0 && < 0.3"
  mtl: ">= 2.2.2 && < 3"
  split: ">= 0.2.3.4 && < 0.3"
  tasty-hunit: ">= 0.10.0.1 && < 0.11"
  text: ">= 2.0 && < 3"
  avh4-lib: {}


library:
  source-dirs:
    - src

  exposed-modules:
    - CommandLine.TestWorld
    - Data.FileTree
    - Expect


tests:
  elm-format-test-lib-tests:
    main: Tests.hs
    source-dirs:
      - test
      - src

    dependencies:
      tasty: ">= 1.2 && < 2"
      tasty-hspec: ">= 1.2.0.1 && < 1.3"

    build-tools:
      tasty-discover: ">= 4.2.1 && < 5"
