Vagrant.configure(2) do |config|
  config.vm.box = "opentable/win-2012r2-standard-amd64-nocm"

  config.vm.communicator = "winrm"

  config.vm.provision :shell, path: "shell/main.cmd"
  config.vm.provision :shell, path: "shell/InstallPackages.bat"
end
