name: avh4-lib
version: 0.0.0.1

synopsis: Common code for haskell projects
license: BSD-3-Clause
license-file: LICENSE
author:     Aaron VonderHaar
maintainer: gruen0aermel@gmail.com
copyright:  See https://github.com/avh4/elm-format/blob/master/LICENSE

build-type: Simple

language: Haskell2010

default-extensions:
  - DeriveFunctor
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - ScopedTypeVariables

ghc-options:
  - -O2
  - -Wall
  - -Werror=unused-packages
  - -Wno-name-shadowing

dependencies:
  array: ">= 0.5.4.0 && < 0.6"
  base: ">= 4.15.0.0 && < 5"
  bytestring: ">= 0.11.3.0 && < 0.12"
  directory: ">= 1.3.6.2 && < 2"
  filepath: ">= 1.4.2.1 && < 2"
  mtl: ">= 2.2.2 && < 3"
  pooled-io: ">= 0.0.2 && < 0.1"
  process: ">= 1.6.13.2 && < 2"
  relude: ">= 1.1.0.0 && < 1.3"
  text: ">= 2.0 && < 3"


library:
  source-dirs:
    - src


tests:
  al-tests:
    main: Tests.hs
    source-dirs:
      - test
      - src

    dependencies:
      tasty: ">= 1.2 && < 2"
      tasty-hunit: ">= 0.10.0.1 && < 0.11"

    build-tools:
      tasty-discover: ">= 4.2.1 && < 5"
