name: elm-format-lib
version: 0.0.0.1

synopsis: Common code used by elm-format and elm-refactor
license: BSD-3-Clause
license-file: LICENSE
author:     Aaron VonderHaar
maintainer: gruen0aermel@gmail.com
copyright:  See https://github.com/avh4/elm-format/blob/master/LICENSE

build-type: Simple

language: Haskell2010

default-extensions:
  - DeriveFunctor
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - ScopedTypeVariables

ghc-options:
  - -O2
  - -Wall
  - -Werror=unused-packages
  - -Wno-name-shadowing

dependencies:
  aeson: ">= 2.1.0.0 && < 2.2"
  base: ">= 4.15.0.0 && < 5"
  bimap: ">= 0.4.0 && < 0.6"
  binary: ">= 0.8.9.0 && < 0.9"
  bytestring: ">= 0.11.3.0 && < 0.12"
  containers: ">= 0.6.5.1 && < 0.7"
  mtl: ">= 2.2.2 && < 3"
  optparse-applicative: ">= 0.17.0.0 && < 0.18"
  relude: ">= 1.1.0.0 && < 1.3"
  text: ">= 2.0 && < 3"
  avh4-lib: {}
  elm-format-markdown: {}


library:
  source-dirs:
    - src

  exposed-modules:
    - AST.Listing
    - AST.MatchReferences
    - AST.Module
    - AST.Structure
    - AST.V0_16
    - CommandLine.InfoFormatter
    - CommandLine.Program
    - CommandLine.ResolveFiles
    - CommandLine.TransformFiles
    - ElmFormat.AST.PublicAST
    - ElmFormat.AST.Shared
    - ElmFormat.ImportInfo
    - ElmFormat.KnownContents
    - ElmFormat.Parse
    - ElmFormat.Render.Markdown
    - ElmFormat.Render.Text
    - ElmVersion
    - Parse.Markdown
    - Reporting.Annotation
    - Reporting.Error.Syntax
    - Reporting.Result


tests:
  efl-tests:
    main: Tests.hs
    source-dirs:
      - test
      - src

    dependencies:
      hspec: ">= 2.7.4 && < 3"
      split: ">= 0.2.3.4 && < 0.3"
      tasty: ">= 1.2 && < 2"
      tasty-hspec: ">= 1.2.0.1 && < 1.3"
      tasty-hunit: ">= 0.10.0.1 && < 0.11"
      elm-format-test-lib: {}

    build-tools:
      tasty-discover: ">= 4.2.1 && < 5"
