name: CI - Windows

on:
  push:
    branches: '*'
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Configure environment
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Install stack
      shell: powershell
      run: |
        mkdir -p ~/stack-install
        cd ~/stack-install
        Invoke-WebRequest -OutFile ~/stack-install/stack.zip https://get.haskellstack.org/stable/windows-x86_64.zip
        7z x stack.zip stack.exe
        echo "::add-path::$HOME/stack-install"
    - uses: actions/cache@v2.1.1
      with:
        path: ~\AppData\Roaming\stack
        key: ${{ runner.os }}-stack
    - run: stack --version
    - run: stack setup
    - run: stack build --only-dependencies
    - run: stack install shake
    - name: Build
      run: stack runhaskell Shakefile.hs -- build
    - name: Tests
      run: |
        stack runhaskell Shakefile.hs -- _build/stack-test.ok
        echo "WARNING: integration tests are currently disabled on Windows CI"
