name: Snapshot release

on:
  push:
    branches:
      - 'json'
      - 'new-parser-2021'

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        # - windows-latest

    name: snapshot-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Configure environment
      run: |
        git config --global core.autocrlf false
    - name: Configure SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SNAPSHOT_SSH_KEY }}
        known_hosts: ${{ secrets.SNAPSHOT_KNOWN_HOSTS }}
    - uses: actions/checkout@v2
    - name: Workaround for https://github.com/actions/checkout/issues/290
      run: git fetch --tags --prune --unshallow --force
    - uses: haskell/actions/setup@v1
      name: Setup Haskell
      id: setup-haskell
      with:
        ghc-version: 9.0.2
    - name: Verify Haskell version
      run: |
        cabal --version
        ghc --version
        [[ $(ghc --numeric-version) == 9.0.2 ]]
    - uses: actions/cache@v2
      name: Cache cabal-release-v1-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: cabal-release-v1-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
    - run: cabal v2-update
    - run: ./build.sh -- dist-dependencies
    - run: ./build.sh -- dist
    - name: Upload snapshot
      run: rsync -va dist/ "${{ secrets.SNAPSHOT_DEST }}/${BRANCH#refs/heads/}/$(git describe)/"
      env:
        BRANCH: ${{ github.ref }}
